all:
	@cd findFirst && make
	@cd forEvery && make
	@cd forEveryTrans && make
	@cd simple && make
	@cd txCounter && make
	@cd dynamic && make

clean:
	@cd findFirst && make clean
	@cd forEvery && make clean
	@cd forEveryTrans && make clean
	@cd simple && make clean
	@cd txCounter && make clean
	@cd dynamic && make clean
